### ISSUE TITLE
set-output deprecation

### ISSUE THREAD

**Issue by enumag** [MrOctopus/download-asset-action#6]
While using this I got this warning in the log:

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Comment by per1234** [comment]
This can be fixed by bumping the project's [`@actions/core` package](https://www.npmjs.com/package/@actions/core) dependency to 1.10.0, which migrates the commands from the deprecated environment variable-based implementation to the new "environment file"-based implementation:

https://github.com/actions/toolkit/pull/1178

**Comment by MrOctopus** [comment]
Fixed in the[ latest release](https://github.com/MrOctopus/download-asset-action/releases/tag/1.1). Apologies for the late fix.
